name: ci

on:
  push:
    branches:
      - "master"
    tags:
      - "v*.*.*" # 匹配以 v 开头，后跟三个数字的标签

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags:
            - star7th/showdoc:latest
            - star7th/showdoc:${{ github.ref }}
            - star7th/showdoc:${{ github.ref | replace('refs/tags/','') }}
